spring:
  datasource:
    url: jdbc:sqlserver://101.37.160.171:1433;DatabaseName=TLGDB
    username: interface
    password: Lanyueyang@
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: sql_server





#  devtools:
#    restart:
#      enabled: true
logging:
  path: d:/
  level: trace
  config: classpath:logback-spring-dev.xml

server:
  port: 8888

filePath: D:\files

test:
      name : jerry
      age: 19

